name: CI

# Only trigger, when the submodules workflow succeeded
on:
  push:
    branches:
      - main
    paths:
      - docs/**

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r docs/requirements.txt
      - name: Build JupyterBook
        working-directory: ./docs
        run: |
          jupyter-book build .
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_build/html
